package com.company.enums;

public enum CustomerStatus {
    STARTED,
    SHARE_CONTACT,
    CLICKED_ADD_PRODUCT,
    SELECT_CATEGORY_FOR_ADD_PRODUCT,
    ENTERED_PRODUCT_NAME,
    ENTERED_PRODUCT_PRICE,
    SEND_PRODUCT_IMAGE,
    DELETE_PRODUCT,
    COMMIT_OR_ROLLBACK_ADD_PRODUCT;
}
